hostname="apu2-2.lab"

# Management
ifconfig_igb0="inet 192.168.100.42/24"
ifconfig_igb0_ipv6="inet6 2a01:e0a:1092:3d20:dead:beef::42/64"
sshd_enable="YES"

ntpdate_enable="YES"
ntpdate_hosts="192.168.100.1"
ntpdate_flags="-b"

# IPv4 router
gateway_enable="YES"
ifconfig_igb1="inet 198.18.0.205/24 -tso4 -tso6 -lro -vlanhwtso"
ifconfig_igb2="inet 198.19.0.205/24 -tso4 -tso6 -lro -vlanhwtso"
route_generator="-net 198.18.0.0/16 198.18.0.203"
route_receiver="-net 198.19.0.0/16 198.19.0.203"
static_routes="generator receiver"
static_arp_sender="198.18.0.203 0c:c4:7a:ab:29:35"
static_arp_receiver="198.19.0.203 0c:c4:7a:ab:29:36"
static_arp_pairs="sender receiver"

# IPv6 router
ipv6_gateway_enable="YES"
ipv6_activate_all_interfaces="YES"
ifconfig_igb1_ipv6="inet6 2001:2::205/64"
ifconfig_igb2_ipv6="inet6 2001:2:0:8000::205/64"
ipv6_route_generator="2001:2:: -prefixlen 49 2001:2::203"
ipv6_route_receiver="2001:2:0:8000:: -prefixlen 49 2001:2:0:8000::203"
ipv6_static_routes="generator receiver"
static_ndp_pairs="sender receiver"
static_ndp_sender="2001:2::203 0c:c4:7a:ab:29:35"
static_ndp_receiver="2001:2:0:8000::203 0c:c4:7a:ab:29:36"
