#!/bin/sh

# PROVIDE:	bindqueue
# REQUIRE:	FILESYSTEMS netif
# KEYWORD:	nojail

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# chelsio_enable (bool):   Set to YES by default.
#               Set it to YES to bind interrupt threads to different cores

. /etc/rc.subr

name="bindqueue"
rcvar=${name}_enable

start_cmd="bindqueue_start"

bindqueue_start()
{
	#NQ=`/sbin/sysctl -ni dev.cxl.0.nrxq`
	NQ=`/sbin/sysctl -ni hw.ix.num_queues`	
	#On this setup, hw.ix.num_queues=8
	if [ -z "${NQ}" ]; then
		exit 0;
	fi
	NCPU=`/sbin/sysctl -n hw.ncpu`
	#On this setup, hw.ncpu=16
	if [ ${NCPU} -le 2 ]; then
		exit 0
	fi
	#NCPU=$((NCPU - 2))
	CPU=0
	for IRQ in `/usr/bin/vmstat -ai |\
	    /usr/bin/sed -nE '/ix0:que/ s/irq([[:digit:]]+):.*/\1/p'`; do
		/usr/bin/cpuset -l ${CPU} -x ${IRQ}
		CPU=$(((CPU + 1) % NCPU))
	done
	CPU=8
	for IRQ in `/usr/bin/vmstat -ai |\
	    /usr/bin/sed -nE '/ix1:que/ s/irq([[:digit:]]+):.*/\1/p'`; do
		/usr/bin/cpuset -l ${CPU} -x ${IRQ}
		CPU=$(((CPU + 1) % NCPU))
	done
}

load_rc_config $name

: ${bindqueue_enable="YES"}

run_rc_command "$1"

