#!/bin/sh
# Generate all configurations from the 24-default
set -eu
templatedir="24-default"
if [ ! -d ${templatedir} ]; then
	echo "No folder ${templatedir}"
	exit 1
fi

for queue in $(jot 23); do
	[ -d $queue ] && rm -rf $queue
	cp -r ${templatedir} $queue
	cat <<EOF >> $queue/boot/loader.conf.local

# Limiting number of queue to ${queue}
dev.mce.0.conf.channels=${queue}
dev.mce.1.conf.channels=${queue}
EOF
done
