#!/bin/sh
# Generate rules
# Input: number of dummy static routes to add
set -eu

# An usefull function (from: http://code.google.com/p/sh-die/)
die() { echo -n "EXIT: " >&2; echo "$@" >&2; exit 1; }

usage () {
	echo "usage: $0 source-first source-last dst-first dst-last"
	echo "$0 10.1 10.8 10.1 10.8"
	exit 0
}

generator()
{
	count=0
	for src_a in $(jot - $ipsrc_end_a $ipsrc_start_a); do
		for src_b in $(jot - $ipsrc_end_b $ipsrc_start_b); do
			for dst_a in $(jot - $ipdst_end_a $ipdst_start_a); do
				for dst_b in $(jot - $ipdst_end_b $ipdst_start_b); do
					echo "$AF $proto 198.18.$src_a.$src_b $src_port 198.19.$dst_a.$dst_b $dst_port"
				done
			done
		done
	done
}

[ $# -ne 4 ] && usage

ipsrc_start_a=$(echo $1 | cut -d '.' -f 1)
ipsrc_start_b=$(echo $1 | cut -d '.' -f 2)
ipsrc_end_a=$(echo $2 | cut -d '.' -f 1)
ipsrc_end_b=$(echo $2 | cut -d '.' -f 2)
ipdst_start_a=$(echo $3 | cut -d '.' -f 1)
ipdst_start_b=$(echo $3 | cut -d '.' -f 2)
ipdst_end_a=$(echo $4 | cut -d '.' -f 1)
ipdst_end_b=$(echo $4 | cut -d '.' -f 2)

AF=4
proto=17
src_port=2000
dst_port=2000

generator
